version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "Using image tag: $IMAGE_TAG"

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG

      - echo Writing imagedefinitions.json (optional)...
      - printf '[{"name":"flask-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

      - echo Replacing image tag in ECS task definition...
      - sed -i "s|\$IMAGE_TAG|$IMAGE_TAG|g" task-definition.json

      - echo Registering new ECS task definition revision...
      - aws ecs register-task-definition \
          --cli-input-json file://task-definition.json \
          --region $AWS_DEFAULT_REGION

      - echo Updating ECS service...
      - LATEST_REVISION=$(aws ecs describe-task-definition \
          --task-definition $TASK_DEFINITION_NAME \
          --region $AWS_DEFAULT_REGION \
          --query "taskDefinition.revision" --output text)

      - aws ecs update-service \
          --cluster $CLUSTER_NAME \
          --service $SERVICE_NAME \
          --task-definition $TASK_DEFINITION_NAME:$LATEST_REVISION \
          --force-new-deployment \
          --region $AWS_DEFAULT_REGION

      - echo "✅ ECS service updated successfully."
